Repository grpc/grpc-swift-nio-transport, pull requests merged in 2024-10, with the labels that each got.

#7 Update generateed code and tests
  IntegrationTests/grpc-performance-tests/Sources/BenchmarkClient.swift
  IntegrationTests/grpc-performance-tests/Sources/BenchmarkService.swift
  IntegrationTests/grpc-performance-tests/Sources/Generated/grpc_testing_benchmark_service.grpc.swift
  IntegrationTests/grpc-performance-tests/Sources/Generated/grpc_testing_worker_service.grpc.swift
  IntegrationTests/grpc-performance-tests/Sources/WorkerService.swift
  Tests/GRPCNIOTransportHTTP2Tests/ControlClient.swift
  Tests/GRPCNIOTransportHTTP2Tests/ControlService.swift
  Tests/GRPCNIOTransportHTTP2Tests/HTTP2TransportTests.swift
Labels: semver/none

#8 Set grpc-swift version to 2.0.0-alpha.1
  Package.swift
Labels: semver/patch

#9 Add README, docs and .spi.yml
  .spi.yml
  CONTRIBUTING.md
  Package.swift
  README.md
  SECURITY.md
  Sources/GRPCNIOTransportHTTP2/Documentation.docc/Documentation.md
Labels: semver/none

#11 Surface transient channel errors
  Sources/GRPCNIOTransportCore/Client/Connection/Connection.swift
  Sources/GRPCNIOTransportCore/Client/Connection/ConnectivityState.swift
  Sources/GRPCNIOTransportCore/Client/Connection/GRPCChannel.swift
  Sources/GRPCNIOTransportCore/Client/Connection/LoadBalancers/RoundRobinLoadBalancer.swift
  Sources/GRPCNIOTransportCore/Client/Connection/LoadBalancers/Subchannel.swift
  Sources/GRPCNIOTransportCore/Internal/Result+Catching.swift
  Tests/GRPCNIOTransportCoreTests/Client/Connection/Connection+Equatable.swift
  Tests/GRPCNIOTransportCoreTests/Client/Connection/LoadBalancers/SubchannelTests.swift
Labels: semver/minor

#13 Add support for RPC cancellation
  Package.swift
  Sources/GRPCNIOTransportCore/Internal/NIOChannelPipeline+GRPC.swift
  Sources/GRPCNIOTransportCore/Server/CommonHTTP2ServerTransport.swift
  Sources/GRPCNIOTransportCore/Server/GRPCServerStreamHandler.swift
  Tests/GRPCNIOTransportCoreTests/Client/Connection/Utilities/ConnectionTest.swift
  Tests/GRPCNIOTransportCoreTests/Client/Connection/Utilities/TestServer.swift
  Tests/GRPCNIOTransportCoreTests/Server/GRPCServerStreamHandlerTests.swift
  Tests/GRPCNIOTransportHTTP2Tests/ControlClient.swift
  Tests/GRPCNIOTransportHTTP2Tests/ControlMessages.swift
  Tests/GRPCNIOTransportHTTP2Tests/ControlService.swift
  Tests/GRPCNIOTransportHTTP2Tests/HTTP2TransportTests.swift
Labels: semver/patch

#12 Add E2E tests with TLS enabled
  Package.swift
  Sources/GRPCNIOTransportHTTP2Posix/TLSConfig.swift
  Sources/GRPCNIOTransportHTTP2TransportServices/TLSConfig.swift
  Tests/GRPCNIOTransportHTTP2Tests/HTTP2TransportTLSEnabledTests.swift
Labels: semver/minor

#14 Move server connection management tests to swift-testing
  Sources/GRPCNIOTransportCore/Server/Connection/ServerConnectionManagementHandler.swift
  Tests/GRPCNIOTransportCoreTests/Server/Connection/ServerConnectionManagementHandlerTests.swift
  Tests/GRPCNIOTransportCoreTests/XCTest+FramePayload.swift
Labels: semver/patch

#15 Move client connection handler tests to swift-testing
  Tests/GRPCNIOTransportCoreTests/Client/Connection/ClientConnectionHandlerTests.swift
Labels: semver/none

#16 Close channel on errors
  Sources/GRPCNIOTransportCore/Client/Connection/ClientConnectionHandler.swift
  Sources/GRPCNIOTransportCore/Server/Connection/ServerConnectionManagementHandler+StateMachine.swift
  Sources/GRPCNIOTransportCore/Server/Connection/ServerConnectionManagementHandler.swift
  Tests/GRPCNIOTransportCoreTests/Client/Connection/ClientConnectionHandlerTests.swift
  Tests/GRPCNIOTransportCoreTests/HTTP2Frame+Helpers.swift
  Tests/GRPCNIOTransportCoreTests/Server/Connection/ServerConnectionManagementHandlerTests.swift
Labels: semver/patch
