Repository grpc/grpc-swift-nio-transport, pull requests merged in 2024-11, with the labels that each got.

#23 Add more build settings to test targets
  Package.swift
  Tests/GRPCNIOTransportCoreTests/Client/Connection/Connection+Equatable.swift
  Tests/GRPCNIOTransportCoreTests/GRPCStreamStateMachineTests.swift
Labels: semver/patch

#24 Fixup soundness checks
  .github/workflows/pull_request.yml
  .github/workflows/soundness.yml
  .licenseignore
  .swiftformatignore
  .unacceptablelanguageignore
Labels: semver/none

#25 Remove '@_exported import GRPCCore'
  Package.swift
  Sources/GRPCNIOTransportHTTP2/Exports.swift
  Sources/GRPCNIOTransportHTTP2Posix/Exports.swift
  Sources/GRPCNIOTransportHTTP2TransportServices/Exports.swift
  Tests/GRPCNIOTransportHTTP2Tests/HTTP2TransportTLSEnabledTests.swift
Labels: semver/patch

#22 Remove '#if canImport(NIOSSL)'
  Sources/GRPCNIOTransportHTTP2Posix/HTTP2ClientTransport+Posix.swift
  Sources/GRPCNIOTransportHTTP2Posix/HTTP2ServerTransport+Posix.swift
  Sources/GRPCNIOTransportHTTP2Posix/NIOSSL+GRPC.swift
  Sources/GRPCNIOTransportHTTP2Posix/TLSConfig.swift
  Tests/GRPCNIOTransportHTTP2Tests/HTTP2TransportNIOPosixTests.swift
Labels: semver/patch

#26 Pre-emptively fix sendability issues with the next NIO release
  Sources/GRPCNIOTransportHTTP2Posix/HTTP2ServerTransport+Posix.swift
  Sources/GRPCNIOTransportHTTP2TransportServices/HTTP2ServerTransport+TransportServices.swift
Labels: semver/patch

#18 Add support for additional TLS options in NIOTS transport
  Sources/GRPCNIOTransportCore/Client/Connection/ClientConnectionHandler.swift
  Sources/GRPCNIOTransportCore/TLSConfig.swift
  Sources/GRPCNIOTransportHTTP2Posix/Config+TLS.swift
  Sources/GRPCNIOTransportHTTP2Posix/HTTP2ClientTransport+Posix.swift
  Sources/GRPCNIOTransportHTTP2TransportServices/Config+TLS.swift
  Sources/GRPCNIOTransportHTTP2TransportServices/HTTP2ClientTransport+TransportServices.swift
  Sources/GRPCNIOTransportHTTP2TransportServices/HTTP2ServerTransport+TransportServices.swift
  Sources/GRPCNIOTransportHTTP2TransportServices/TLSConfig.swift
  Tests/GRPCNIOTransportHTTP2Tests/HTTP2TransportNIOTransportServicesTests.swift
Labels: semver/minor

#28 Use NIO scheduleCallback API for connection handler timers
  Package.swift
  Sources/GRPCNIOTransportCore/Client/Connection/ClientConnectionHandler.swift
  Sources/GRPCNIOTransportCore/Internal/Timer.swift
  Sources/GRPCNIOTransportCore/Server/Connection/ServerConnectionManagementHandler.swift
  Tests/GRPCNIOTransportCoreTests/Internal/TimerTests.swift
Labels: semver/patch

#31 Use new descriptor API
  Sources/GRPCNIOTransportCore/GRPCStreamStateMachine.swift
  Sources/GRPCNIOTransportCore/Internal/MethodConfigs.swift
  Tests/GRPCNIOTransportCoreTests/Client/GRPCClientStreamHandlerTests.swift
  Tests/GRPCNIOTransportCoreTests/GRPCStreamStateMachineTests.swift
  Tests/GRPCNIOTransportCoreTests/Server/GRPCServerStreamHandlerTests.swift
  Tests/GRPCNIOTransportCoreTests/Test Utilities/MethodDescriptor+Common.swift
  Tests/GRPCNIOTransportHTTP2Tests/ControlClient.swift
  Tests/GRPCNIOTransportHTTP2Tests/ControlService.swift
Labels: semver/patch
