Repository grpc/grpc-swift-nio-transport, pull requests merged in 2024-09, with the labels that each got.

#2 Add missing linker settings for zlib
  Package.swift
Labels: semver/patch

#3 Add integration tests
  .github/workflows/ci.yaml
  IntegrationTests/grpc-interop-tests/.gitignore
  IntegrationTests/grpc-interop-tests/Package.swift
  IntegrationTests/grpc-interop-tests/Sources/InteroperabilityTestsExecutable.swift
  IntegrationTests/grpc-performance-tests/.gitignore
  IntegrationTests/grpc-performance-tests/Package.swift
  IntegrationTests/grpc-performance-tests/Sources/BenchmarkClient.swift
  IntegrationTests/grpc-performance-tests/Sources/BenchmarkService.swift
  IntegrationTests/grpc-performance-tests/Sources/Generated/grpc_core_stats.pb.swift
  IntegrationTests/grpc-performance-tests/Sources/Generated/grpc_testing_benchmark_service.grpc.swift
  IntegrationTests/grpc-performance-tests/Sources/Generated/grpc_testing_benchmark_service.pb.swift
  IntegrationTests/grpc-performance-tests/Sources/Generated/grpc_testing_control.pb.swift
  IntegrationTests/grpc-performance-tests/Sources/Generated/grpc_testing_messages.pb.swift
  IntegrationTests/grpc-performance-tests/Sources/Generated/grpc_testing_payloads.pb.swift
  IntegrationTests/grpc-performance-tests/Sources/Generated/grpc_testing_stats.pb.swift
  IntegrationTests/grpc-performance-tests/Sources/Generated/grpc_testing_worker_service.grpc.swift
  IntegrationTests/grpc-performance-tests/Sources/Generated/grpc_testing_worker_service.pb.swift
  IntegrationTests/grpc-performance-tests/Sources/PerformanceWorker.swift
  IntegrationTests/grpc-performance-tests/Sources/RPCStats.swift
  IntegrationTests/grpc-performance-tests/Sources/ResourceUsage.swift
  IntegrationTests/grpc-performance-tests/Sources/WorkerService.swift
  dev/build-performance-tests.sh
  dev/format.sh
  dev/license-check.sh
  dev/protos/README.md
  dev/protos/fetch.sh
  dev/protos/generate.sh
  dev/protos/tests/interoperability/src/proto/grpc/testing/empty.proto
  dev/protos/tests/interoperability/src/proto/grpc/testing/empty_service.proto
  dev/protos/tests/interoperability/src/proto/grpc/testing/messages.proto
  dev/protos/tests/interoperability/src/proto/grpc/testing/test.proto
  dev/protos/upstream/grpc/core/stats.proto
  dev/protos/upstream/grpc/testing/benchmark_service.proto
  dev/protos/upstream/grpc/testing/control.proto
  dev/protos/upstream/grpc/testing/messages.proto
  dev/protos/upstream/grpc/testing/payloads.proto
  dev/protos/upstream/grpc/testing/stats.proto
  dev/protos/upstream/grpc/testing/worker_service.proto
  dev/run-interop-tests.sh
Labels: semver/none

#5 Add a DNS NameResolver
  Sources/GRPCNIOTransportCore/Client/Resolver/NameResolver+DNS.swift
  Sources/GRPCNIOTransportCore/Client/Resolver/NameResolverRegistry.swift
  Tests/GRPCNIOTransportCoreTests/Client/Resolver/NameResolverRegistryTests.swift
Labels: semver/minor

#6 Default Wait for Ready to false
  Sources/GRPCNIOTransportCore/Client/Connection/GRPCChannel.swift
Labels: semver/patch
