Repository grpc/grpc-swift-nio-transport, pull requests merged in 2024-12, with the labels that each got.

#35 Update pull_request_label.yml
  .github/workflows/pull_request_label.yml
Labels: semver/none

#33 Propagate the authority pseudoheader
  Sources/GRPCNIOTransportCore/Client/Connection/Connection.swift
  Sources/GRPCNIOTransportCore/Client/Connection/ConnectionFactory.swift
  Sources/GRPCNIOTransportCore/Client/Connection/GRPCChannel.swift
  Sources/GRPCNIOTransportCore/Client/Connection/LoadBalancers/PickFirstLoadBalancer.swift
  Sources/GRPCNIOTransportCore/Client/Connection/LoadBalancers/RoundRobinLoadBalancer.swift
  Sources/GRPCNIOTransportCore/Client/Connection/LoadBalancers/Subchannel.swift
  Sources/GRPCNIOTransportCore/Client/GRPCClientStreamHandler.swift
  Sources/GRPCNIOTransportCore/Client/HTTP2ClientTransport.swift
  Sources/GRPCNIOTransportCore/Client/Resolver/NameResolver+DNS.swift
  Sources/GRPCNIOTransportCore/Client/Resolver/NameResolver+UDS.swift
  Sources/GRPCNIOTransportCore/Client/Resolver/NameResolver.swift
  Sources/GRPCNIOTransportCore/Client/Resolver/SocketAddress.swift
  Sources/GRPCNIOTransportCore/GRPCStreamStateMachine.swift
  Sources/GRPCNIOTransportCore/Internal/PercentEncoding.swift
  Sources/GRPCNIOTransportHTTP2Posix/Config+TLS.swift
  Sources/GRPCNIOTransportHTTP2Posix/HTTP2ClientTransport+Posix.swift
  Sources/GRPCNIOTransportHTTP2TransportServices/Config+TLS.swift
  Sources/GRPCNIOTransportHTTP2TransportServices/HTTP2ClientTransport+TransportServices.swift
  Tests/GRPCNIOTransportCoreTests/Client/Connection/ConnectionTests.swift
  Tests/GRPCNIOTransportCoreTests/Client/Connection/LoadBalancers/LoadBalancerTest.swift
  Tests/GRPCNIOTransportCoreTests/Client/Connection/LoadBalancers/RoundRobinLoadBalancerTests.swift
  Tests/GRPCNIOTransportCoreTests/Client/Connection/LoadBalancers/SubchannelTests.swift
  Tests/GRPCNIOTransportCoreTests/Client/Connection/Utilities/ConnectionTest.swift
  Tests/GRPCNIOTransportCoreTests/Client/Connection/Utilities/HTTP2Connectors.swift
  Tests/GRPCNIOTransportCoreTests/Client/GRPCClientStreamHandlerTests.swift
  Tests/GRPCNIOTransportCoreTests/Client/Resolver/SocketAddressTests.swift
  Tests/GRPCNIOTransportCoreTests/GRPCStreamStateMachineTests.swift
  Tests/GRPCNIOTransportCoreTests/Internal/PercentEncodingTests.swift
  Tests/GRPCNIOTransportHTTP2Tests/HTTP2TransportNIOTransportServicesTests.swift
  Tests/GRPCNIOTransportHTTP2Tests/HTTP2TransportTLSEnabledTests.swift
  Tests/GRPCNIOTransportHTTP2Tests/HTTP2TransportTests.swift
Labels: semver/minor

#36 Add remote peer info
  Sources/GRPCNIOTransportCore/Server/CommonHTTP2ServerTransport.swift
  Sources/GRPCNIOTransportHTTP2Posix/HTTP2ServerTransport+Posix.swift
  Tests/GRPCNIOTransportHTTP2Tests/ControlClient.swift
  Tests/GRPCNIOTransportHTTP2Tests/ControlService.swift
  Tests/GRPCNIOTransportHTTP2Tests/HTTP2TransportTests.swift
Labels: ⚠️ semver/major

#38 Delay closing until the next loop tick when gracefully shutting down
  Sources/GRPCNIOTransportCore/Client/Connection/ClientConnectionHandler.swift
  Sources/GRPCNIOTransportCore/Server/Connection/ServerConnectionManagementHandler.swift
Labels: semver/patch

#19 Make sure we don't write additional DATA frames when flushing once request is finished
  Sources/GRPCNIOTransportCore/Client/GRPCClientStreamHandler.swift
  Tests/GRPCNIOTransportCoreTests/Client/GRPCClientStreamHandlerTests.swift
Labels: semver/patch

#34 Add index pages for posix and niots transports
  Sources/GRPCNIOTransportHTTP2Posix/Documentation.docc/Documentation.md
  Sources/GRPCNIOTransportHTTP2TransportServices/Documentation.docc/Documentation.md
Labels: semver/none

#39 Bump dependency version
  Package.swift
Labels: semver/patch

#42 Modify which symbols are documented
  .spi.yml
Labels: semver/none

#44 Workaround #43 in tests
  Tests/GRPCNIOTransportHTTP2Tests/HTTP2TransportTests.swift
Labels: semver/none

#41 Reconnect when making streams and the LB is idle
  Sources/GRPCNIOTransportCore/Client/Connection/GRPCChannel.swift
  Tests/GRPCNIOTransportCoreTests/Client/Connection/GRPCChannelTests.swift
Labels: semver/patch

#20 Add NIOTS transport to E2E TLS-enabled tests
  Package.swift
  Tests/GRPCNIOTransportHTTP2Tests/HTTP2TransportNIOTransportServicesTests.swift
  Tests/GRPCNIOTransportHTTP2Tests/HTTP2TransportTLSEnabledTests.swift
  Tests/GRPCNIOTransportHTTP2Tests/Test Utilities/SelfSignedCertificateKeyPairs.swift
Labels: semver/patch

#47 Avoid using accidental public API
  NOTICES.txt
  Sources/GRPCNIOTransportCore/GRPCStreamStateMachine.swift
  Sources/GRPCNIOTransportCore/Internal/Base64.swift
Labels: semver/patch

#45 Enable MemberImportVisibility check on all targets
  Package.swift
Labels: semver/none

#46 Fix TLS E2E test flakiness
  Tests/GRPCNIOTransportHTTP2Tests/HTTP2TransportTLSEnabledTests.swift
Labels: semver/none

#48 Update release.yml
  .github/release.yml
Labels: semver/none

#49 Reset go away state
  Sources/GRPCNIOTransportCore/Client/Connection/LoadBalancers/PickFirstLoadBalancer.swift
  Tests/GRPCNIOTransportCoreTests/Client/Connection/LoadBalancers/PickFirstLoadBalancerTests.swift
Labels: 🔨 semver/patch

#50 Fix keepalive logic
  Sources/GRPCNIOTransportCore/Internal/NIOChannelPipeline+GRPC.swift
  Sources/GRPCNIOTransportCore/Server/Connection/ServerConnectionManagementHandler.swift
  Sources/GRPCNIOTransportCore/Server/GRPCServerStreamHandler.swift
  Tests/GRPCNIOTransportCoreTests/Client/Connection/Utilities/ConnectionTest.swift
  Tests/GRPCNIOTransportCoreTests/Client/Connection/Utilities/TestServer.swift
  Tests/GRPCNIOTransportCoreTests/Server/GRPCServerStreamHandlerTests.swift
Labels: 🔨 semver/patch

#51 Bump version
  Package.swift
Labels: 🔨 semver/patch
