Repository grpc/grpc-swift-nio-transport, pull requests merged in 2025-01, with the labels that each got.

#53 Increase minimum `swift-nio-http2` version
  Package.swift
Labels: 🔨 semver/patch

#54 Fix warnings from new NIO
  Package.swift
  Sources/GRPCNIOTransportCore/Internal/Base64.swift
  Tests/GRPCNIOTransportCoreTests/GRPCStreamStateMachineTests.swift
  Tests/GRPCNIOTransportCoreTests/Server/Connection/ServerConnectionManagementHandlerTests.swift
  Tests/GRPCNIOTransportCoreTests/Server/GRPCServerStreamHandlerTests.swift
Labels: 🔨 semver/patch

#56 Adopt `ClientContext` changes
  Package.swift
  Sources/GRPCNIOTransportCore/Client/Connection/Connection.swift
  Sources/GRPCNIOTransportCore/Client/Connection/GRPCChannel.swift
  Sources/GRPCNIOTransportCore/Internal/Channel+AddressInfo.swift
  Sources/GRPCNIOTransportCore/Server/CommonHTTP2ServerTransport.swift
  Sources/GRPCNIOTransportHTTP2Posix/HTTP2ClientTransport+Posix.swift
  Sources/GRPCNIOTransportHTTP2TransportServices/HTTP2ClientTransport+TransportServices.swift
  Tests/GRPCNIOTransportCoreTests/Client/Connection/GRPCChannelTests.swift
  Tests/GRPCNIOTransportHTTP2Tests/ControlClient.swift
  Tests/GRPCNIOTransportHTTP2Tests/ControlService.swift
  Tests/GRPCNIOTransportHTTP2Tests/HTTP2TransportTests.swift
  dev/license-check.sh
Labels: ⚠️ semver/major

#59 Adopt `ServerContext` changes
  Sources/GRPCNIOTransportCore/Internal/Channel+AddressInfo.swift
  Sources/GRPCNIOTransportCore/Server/CommonHTTP2ServerTransport.swift
  Tests/GRPCNIOTransportHTTP2Tests/ControlService.swift
  Tests/GRPCNIOTransportHTTP2Tests/HTTP2TransportTests.swift
Labels: 🆕 semver/minor

#55 Adopt new bag-of-bytes protocol
  IntegrationTests/grpc-interop-tests/Sources/InteroperabilityTestsExecutable.swift
  IntegrationTests/grpc-performance-tests/Sources/BenchmarkClient.swift
  IntegrationTests/grpc-performance-tests/Sources/Generated/grpc_testing_benchmark_service.grpc.swift
  IntegrationTests/grpc-performance-tests/Sources/Generated/grpc_testing_control.grpc.swift
  IntegrationTests/grpc-performance-tests/Sources/Generated/grpc_testing_messages.grpc.swift
  IntegrationTests/grpc-performance-tests/Sources/Generated/grpc_testing_payloads.grpc.swift
  IntegrationTests/grpc-performance-tests/Sources/Generated/grpc_testing_stats.grpc.swift
  IntegrationTests/grpc-performance-tests/Sources/Generated/grpc_testing_worker_service.grpc.swift
  IntegrationTests/grpc-performance-tests/Sources/WorkerService.swift
  Sources/GRPCNIOTransportCore/Client/Connection/Connection.swift
  Sources/GRPCNIOTransportCore/Client/Connection/GRPCChannel.swift
  Sources/GRPCNIOTransportCore/Client/GRPCClientStreamHandler.swift
  Sources/GRPCNIOTransportCore/Compression/Zlib.swift
  Sources/GRPCNIOTransportCore/GRPCMessageDecoder.swift
  Sources/GRPCNIOTransportCore/GRPCMessageFramer.swift
  Sources/GRPCNIOTransportCore/GRPCNIOTransportBytes.swift
  Sources/GRPCNIOTransportCore/GRPCStreamStateMachine.swift
  Sources/GRPCNIOTransportCore/Internal/NIOChannelPipeline+GRPC.swift
  Sources/GRPCNIOTransportCore/Server/CommonHTTP2ServerTransport.swift
  Sources/GRPCNIOTransportCore/Server/Connection/ServerConnection.swift
  Sources/GRPCNIOTransportCore/Server/GRPCServerStreamHandler.swift
  Sources/GRPCNIOTransportHTTP2Posix/HTTP2ClientTransport+Posix.swift
  Sources/GRPCNIOTransportHTTP2Posix/HTTP2ServerTransport+Posix.swift
  Sources/GRPCNIOTransportHTTP2TransportServices/HTTP2ClientTransport+TransportServices.swift
  Sources/GRPCNIOTransportHTTP2TransportServices/HTTP2ServerTransport+TransportServices.swift
  Tests/GRPCNIOTransportCoreTests/Client/Connection/ConnectionTests.swift
  Tests/GRPCNIOTransportCoreTests/Client/Connection/LoadBalancers/SubchannelTests.swift
  Tests/GRPCNIOTransportCoreTests/Client/Connection/Utilities/ConnectionTest.swift
  Tests/GRPCNIOTransportCoreTests/Client/Connection/Utilities/TestServer.swift
  Tests/GRPCNIOTransportCoreTests/Client/GRPCClientStreamHandlerTests.swift
  Tests/GRPCNIOTransportCoreTests/GRPCMessageDecoderTests.swift
  Tests/GRPCNIOTransportCoreTests/GRPCMessageDeframerTests.swift
  Tests/GRPCNIOTransportCoreTests/GRPCMessageFramerTests.swift
  Tests/GRPCNIOTransportCoreTests/GRPCStreamStateMachineTests.swift
  Tests/GRPCNIOTransportCoreTests/Server/Compression/ZlibTests.swift
  Tests/GRPCNIOTransportCoreTests/Server/GRPCServerStreamHandlerTests.swift
  Tests/GRPCNIOTransportHTTP2Tests/ControlClient.swift
  Tests/GRPCNIOTransportHTTP2Tests/ControlMessages.swift
  Tests/GRPCNIOTransportHTTP2Tests/ControlService.swift
  Tests/GRPCNIOTransportHTTP2Tests/HTTP2TransportTLSEnabledTests.swift
  Tests/GRPCNIOTransportHTTP2Tests/HTTP2TransportTests.swift
  Tests/GRPCNIOTransportHTTP2Tests/Test Utilities/TransportKind.swift
Labels: ⚠️ semver/major

#57 Group docs and fix visibility
  .spi.yml
  Sources/GRPCNIOTransportCore/Client/Connection/LoadBalancers/Subchannel.swift
  Sources/GRPCNIOTransportCore/Documentation.docc/Documentation.md
  Sources/GRPCNIOTransportCore/Server/Connection/ServerConnection.swift
Labels: 🔨 semver/patch

#58 Rename the c zlib module
  .licenseignore
  Package.swift
  Sources/CGRPCNIOTransportZlib/empty.c
  Sources/CGRPCNIOTransportZlib/include/CGRPCZlib.h
  Sources/GRPCNIOTransportCore/Compression/Zlib.swift
Labels: 🔨 semver/patch

#61 Move test JSON (de)serializer to its own file
  Tests/GRPCNIOTransportHTTP2Tests/ControlMessages.swift
  Tests/GRPCNIOTransportHTTP2Tests/Test Utilities/JSONSerializing.swift
Labels: semver/none

#52 Add debug channel callbacks
  Sources/GRPCNIOTransportCore/Client/Connection/Connection.swift
  Sources/GRPCNIOTransportCore/Client/Connection/ConnectionFactory.swift
  Sources/GRPCNIOTransportCore/Client/HTTP2ClientTransport.swift
  Sources/GRPCNIOTransportCore/Internal/EventLoopFuture+ChannelInitializer.swift
  Sources/GRPCNIOTransportCore/Internal/NIOChannelPipeline+GRPC.swift
  Sources/GRPCNIOTransportCore/Server/HTTP2ServerTransport.swift
  Sources/GRPCNIOTransportHTTP2Posix/HTTP2ClientTransport+Posix.swift
  Sources/GRPCNIOTransportHTTP2Posix/HTTP2ServerTransport+Posix.swift
  Sources/GRPCNIOTransportHTTP2TransportServices/HTTP2ClientTransport+TransportServices.swift
  Sources/GRPCNIOTransportHTTP2TransportServices/HTTP2ServerTransport+TransportServices.swift
  Tests/GRPCNIOTransportCoreTests/Client/Connection/Utilities/HTTP2Connectors.swift
  Tests/GRPCNIOTransportHTTP2Tests/HTTP2ServerTransport+DebugTests.swift
  Tests/GRPCNIOTransportHTTP2Tests/HTTP2TransportTLSEnabledTests.swift
  Tests/GRPCNIOTransportHTTP2Tests/HTTP2TransportTests.swift
  Tests/GRPCNIOTransportHTTP2Tests/Test Utilities/JSONCoding.swift
  Tests/GRPCNIOTransportHTTP2Tests/Test Utilities/StatsService.swift
  Tests/GRPCNIOTransportHTTP2Tests/Test Utilities/TransportKind.swift
Labels: 🆕 semver/minor

#62 Depend on beta 3 tag
  Package.swift
Labels: semver/none

#63 Remove workaround for issue #43
  Tests/GRPCNIOTransportHTTP2Tests/HTTP2TransportTests.swift
Labels: semver/none

#64 Bump dependency versions
  IntegrationTests/grpc-interop-tests/Package.swift
  IntegrationTests/grpc-performance-tests/Package.swift
  Package.swift
Labels: 🔨 semver/patch

#66 CI use 6.1 nightlies
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
Labels: semver/none

#67 Update dependency requirements
  IntegrationTests/grpc-interop-tests/Package.swift
  IntegrationTests/grpc-performance-tests/Package.swift
  Package.swift
Labels: 🔨 semver/patch
