Repository grpc/grpc-swift-nio-transport, pull requests merged in 2025-09, with the labels that each got.

#125 Support custom verification callback configuration
  Package.swift
  Sources/GRPCNIOTransportHTTP2Posix/Config+TLS.swift
  Sources/GRPCNIOTransportHTTP2Posix/HTTP2ServerTransport+Posix.swift
  Tests/GRPCNIOTransportHTTP2Tests/HTTP2TransportTLSEnabledTests.swift
Labels: 🆕 semver/minor

#126 Enable access to the peer's certificate chain
  Package.swift
  Sources/GRPCNIOTransportHTTP2Posix/HTTP2ServerTransport+Posix.swift
  Sources/GRPCNIOTransportHTTP2Posix/ValidatedCertificateChain.swift
  Tests/GRPCNIOTransportHTTP2Tests/HTTP2TransportTLSEnabledTests.swift
Labels: 🆕 semver/minor

#128 Don't wait for close future if the task is cancelled
  Sources/GRPCNIOTransportCore/Server/CommonHTTP2ServerTransport.swift
  Tests/GRPCNIOTransportHTTP2Tests/HTTP2TransportRegressionTests.swift
  Tests/GRPCNIOTransportHTTP2Tests/Test Utilities/Services/HelloWorld/HelloWorld.grpc.swift
  Tests/GRPCNIOTransportHTTP2Tests/Test Utilities/Services/HelloWorld/HelloWorldService.swift
Labels: 🔨 semver/patch

#129 Enable Swift 6.2 jobs in CI
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
Labels: semver/none
