Repository grpc/grpc-swift-nio-transport, pull requests merged in 2025-07, with the labels that each got.

#117 Deprecate ambiguous IPv4 and IPv6 target APIs
  Package.swift
  Sources/GRPCNIOTransportCore/Client/Resolver/NameResolver+IPv4.swift
  Sources/GRPCNIOTransportCore/Client/Resolver/NameResolver+IPv6.swift
  Sources/GRPCNIOTransportCore/Internal/DebugOnly.swift
  Tests/GRPCNIOTransportCoreTests/Client/Resolver/NameResolverRegistryTests.swift
  Tests/GRPCNIOTransportHTTP2Tests/HTTP2ServerTransport+DebugTests.swift
  Tests/GRPCNIOTransportHTTP2Tests/HTTP2TransportTLSEnabledTests.swift
  Tests/GRPCNIOTransportHTTP2Tests/HTTP2TransportTests.swift
Labels: 🆕 semver/minor

#119 Avoid deprecation warnings
  Package.swift
  Sources/GRPCNIOTransportHTTP2Posix/NIOSSL+GRPC.swift
Labels: 🔨 semver/patch

#121 Enable release mode builds
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
Labels: semver/none
